on:
  push:
    branches: [ "main" ]
jobs:
  nrlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -g nrlint nrlint-plugin-rules-english-node-name
      - run: nrlint flows.json
